package-lock.json, package.json
This PR added the directories that adhere to the mvc model.
=> add mvc directories

.gitignore, package-lock.json, package.json
This PR added handlebars files to the views directory, and installed handlebars. A gitignore file was also added.
=> add handlebars files to views directory

server.js
This PR added the initial code in the server.js file to set up handlebars.
=> set up handlebars in server.js

package-lock.json, package.json, server.js
This PR installed and imported express-session in the server.js file.
=> import session to server.js

.env, controllers/home-routes.js, controllers/index.js, server.js, utils/helpers.js
This PR added routes in the home-routes.js file to render the handlebars files.
=> add handlebars routes

.env, config/connection.js
This PR added variables to the sequelize object  in the connection.js file, so the dotenv file can fill in the mysql username, database name, and password.
=> add env variables in connection.js

db/schema.sql
This PR added some potential data tables for mysql in the schema.sql file. Still needs to be converted to sequelize.
=> added potential tables for database

db/schema.sql
This PR added foreign keys and references to the mysql database scheme as reference for sequelize.
=> added foreign key and ref

db/schema.sql, models/client.js, seeds/client-seeds.js
This PR added seed data to the seeds directory and added code to set up the client table in the client.js file in the models directory.
=> add seed data and table data to client

.env, config/connection.js, controllers/homeRoutes.js, controllers/index.js, controllers/landingPageRoutes.js, controllers/registerRoutes.js, public/css/style.css, public/js/script.js, server.js, views/helpers.handlebars, views/landingpage.handlebars, views/layouts/main.handlebars, views/registerpage.handlebars
added content to the landingpage and registerpage handlebars and created two controller files for landing and register pages to put code in. Also set up some routes to fetch name email and password but havent connected to database yet.
=> added content to the landingpage and registerpage handlebars and created two controller files

.env, controllers/api/client-routes.js, controllers/api/index.js, controllers/index.js, models/index.js, seeds/index.js
This PR added some intial routes, the client model, and seed data for the client table.
=> add routes to client table

models/role.js
This PR added the initial code to set up a table for the "role" values in the models directory.
=> add role table in role directory in models

README.md
This PR is testing Sean's correct email and github account.
=> testing global email

controllers/api/index.js, controllers/api/roleRoutes.js
This PR added a router.get to display all values from the role.js template in models.
=> add role route

models/role.js, seeds/index.js, seeds/role-seeds.js
This PR added role titles to the role template in the models directory.
=> add values to role template in models

controllers/api/helperRoutes.js, models/helper.js
This PR added a router.get to display all the values in the helpers table.
=> add get route for helpers table

models/tasks.js
This PR updated some of the values in the tasks.js table.
=> update columns in tasks table

controllers/api/index.js, controllers/api/landingPageRoutes.js, controllers/api/registerRoutes.js, models/client.js, models/helper.js, views/landingpage.handlebars, views/registerConfirmation.handlebars, views/registerpage.handlebars
Pushing the code up for user registration and login. This code asks for all the required info as per the model to register & uses it to log the user in. Ive added a drop down in the landing page where the user can select if they registered as a client or a helper. They can also add location, only major CA cities for now. The User login is validated before they are granted access to the tasks page. Still need to put code in so that nobody but the user can access the tasks pages
=> Pushing the code up for user registration and login.

.env, controllers/api/helperRoutes.js, controllers/api/index.js, models/index.js, models/tasks.js, seeds/helpers-seeds.js, seeds/index.js, seeds/task-seeds.js
This PR added seed values for the helpers table. The routes for the helpers table has been updated. Can now make a get request for the helpers table.
=> helper table completed

.env
This PR  made a minor change to the dotenv file.
=> change to dotenv

controllers/api/clientRoutes.js, controllers/api/index.js, controllers/api/tasksRoutes.js, models/index.js, models/tasks.js, seeds/client-seeds.js, seeds/index.js, seeds/task-seeds.js
This PR added code to the index.js file in the models directory which helps join the client table with the task table. Can now view client with associated task, and task with associated client.
=> client table and task table joined

.env, models/index.js, models/taskStatus.js, models/tasks.js, seeds/task-seeds.js
This PR added the initial code for the task status model. A relationship to the task table was also set up  in the index.js file in the model directory.
=> add task status model

.env, controllers/api/taskStatusRoutes.js
This PR added the initial code to the taskStatusRoute.js to get all values for task statuses.
=> add get route for task status

controllers/api/helperRoutes.js, controllers/api/tasksRoutes.js, models/helper.js, models/index.js, models/taskStatus.js, models/tasks.js, seeds/task-seeds.js
This PR added code to the index.js file in models which helped join the helper table to the task table. It is now possible to view all tasks with the clients who created the task, the task status, and the helpers who have accepted the task.
=> join helper table to task table

controllers/api/clientRoutes.js
This PR added code to the clientRoutes.js file that allows the user to get each client by id.
=> add get client by id route

controllers/api/clientRoutes.js
This PR added a put route to update client information. The client to update is request by id.
=> add put route for client

controllers/api/clientRoutes.js
This PR added a delete route for the client table to delete a single client. The code still needs work. Getting a 500 error.
=> add delete route for client table

controllers/api/tasksRoutes.js, models/tasks.js
This PR added a post route to the task table. Tasks can now be created and posted to the task table.
=> add post route for tasks

controllers/api/tasksRoutes.js
This PR added a get by id route to the taskRoutes.js file. Tasks can now be requested by id.
=> add get id for task

controllers/api/taskStatusRoutes.js
This PR added a route to the taskStatusRoutes.js file which gets the task status by id.
=> add get status by id

controllers/api/landingPageRoutes.js, controllers/homeRoutes.js, middleware/auth.js, views/registerpage.handlebars
Pushing the code that decodes the JWT webtoken to bring the username which can be used to pull relevant data for that user from the database
=> This code decodes the JWT webtoken to pull data from the DB

controllers/api/landingPageRoutes.js
This PR made a minor change to the landingPageRoutes.js file.
=> minor changes to routes

controllers/api/tasksRoutes.js, controllers/homeRoutes.js, middleware/auth.js, middleware/pullData.js
Changed the middlewares to also fetch helpers data and make it available to whereever the middleware is used
=> Changed the middlewares 

public/css/helpers.css, public/js/helper.js, views/helpers.handlebars
This PR transfered the css code from style.css to helpers.css.
=> transfered style css to helpers css

public/css/helpers.css, public/js/helper.js, views/helpers.handlebars
This PR added a new function to the helpers.js file. The user can now click on the "Get Details" button, and modal with the task details will appear for that specific task.
=> add task details to modal

controllers/api/taskStatusRoutes.js, controllers/api/tasksRoutes.js, models/tasks.js, public/js/helper.js, views/helpers.handlebars
This PR added  put requests to update the task status and the helper associated with the task.
=> add accept button function

public/js/script.js
This PR made a slight change to the script.js file.
=> slight change to script.js

public/js/helper.js
This PR added some of the initial code to get the accepted task list.
=> add initial code to get accepted task list

controllers/api/users.js, controllers/homeRoutes.js, models/tasks.js, public/js/client.js, public/js/script.js, views/clientpage.handlebars
This PR added the necessary code to the client.js file and the homeRoutes.js file to allow the user to post a new task from the client page.
=> add post request to client page

public/css/client.css, public/js/client.js, public/js/helper.js, views/clientpage.handlebars
This PR add a get request for the client page. The user can now see all tasks that user created. A modal was also set up to view the task details.
=> add get requet to client page

public/css/helpers.css, public/js/helper.js
This PR added a slight change to the helpers.css file.
=> add change to helper css

.gitignore
This PR added .env to the gitignore.
=> add dotenv to gitignore
